/**
 * playwright.config.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Central Playwright configuration file.
 * Covers: multi-browser projects, retries, parallelism, reporters,
 * screenshot/video/trace capture, and environment-aware base URLs.
 * ─────────────────────────────────────────────────────────────────────────────
 */

// Load .env variables before anything else
require('dotenv').config();

const { defineConfig, devices } = require('@playwright/test');
const path = require('path');

module.exports = defineConfig({
  // ── Test discovery ────────────────────────────────────────────────────────
  testDir: './tests',
  testMatch: ['**/*.spec.js', '**/*.test.js'],
  testIgnore: ['**/node_modules/**'],

  // ── Execution control ─────────────────────────────────────────────────────
  /* Maximum time (ms) a single test may run before it is considered failed */
  timeout: parseInt(process.env.TEST_TIMEOUT) || 60_000,

  /* Expect (assertion) timeout */
  expect: {
    timeout: parseInt(process.env.EXPECT_TIMEOUT) || 10_000,
  },

  /* Run all tests in parallel by default; set workers=1 for serial */
  fullyParallel: true,
  workers: process.env.CI ? 2 : parseInt(process.env.WORKERS) || 4,

  /* Retry failed tests: 2 times on CI, 0 locally */
  retries: process.env.CI ? 2 : 0,

  /* Stop the whole suite after this many failures (0 = never stop) */
  maxFailures: process.env.CI ? 10 : 0,

  // ── Global setup / teardown ───────────────────────────────────────────────
  globalSetup: require.resolve('./helpers/global-setup.js'),
  globalTeardown: require.resolve('./helpers/global-teardown.js'),

  // ── Shared browser context options ────────────────────────────────────────
  use: {
    /* Base URL — override per project if needed */
    baseURL: process.env.BASE_URL || 'https://the-internet.herokuapp.com',

    /* Headless by default; --headed flag or HEADLESS=false overrides */
    headless: process.env.HEADLESS !== 'false',

    /* Viewport */
    viewport: { width: 1280, height: 720 },

    /* Network & timing */
    navigationTimeout: parseInt(process.env.NAVIGATION_TIMEOUT) || 30_000,
    actionTimeout:     parseInt(process.env.ACTION_TIMEOUT)     || 15_000,

    /* Authentication state — generated by global setup */
    // storageState: './helpers/auth-state.json',

    /* Capture artifacts on failure */
    screenshot: 'only-on-failure',   // 'on' | 'off' | 'only-on-failure'
    video:      'retain-on-failure', // 'on' | 'off' | 'retain-on-failure'
    trace:      'retain-on-failure', // 'on' | 'off' | 'retain-on-failure'

    /* Output folders */
    screenshotsDir: path.join(__dirname, 'screenshots'),
    videosDir:      path.join(__dirname, 'videos'),
    tracesDir:      path.join(__dirname, 'traces'),

    /* Accept all downloads automatically */
    acceptDownloads: true,

    /* Emulate slow network / CPU — useful for stability */
    // launchOptions: { slowMo: 100 },

    /* Extra HTTP headers sent on every request */
    extraHTTPHeaders: {
      'X-Automation': 'playwright',
    },

    /* Ignore HTTPS errors in test environments */
    ignoreHTTPSErrors: process.env.IGNORE_HTTPS_ERRORS === 'true',
  },

  // ── Reporters ─────────────────────────────────────────────────────────────
  reporter: [
    /* Always print a summary to the terminal */
    ['list'],

    /* Rich HTML report — open with: npx playwright show-report reports/html */
    ['html', { outputFolder: 'reports/html', open: 'never' }],

    /* JUnit XML for CI systems (Jenkins, GitHub Actions test-results) */
    ['junit', { outputFile: 'reports/junit/results.xml' }],

    /* JSON — useful for custom post-processing */
    ['json', { outputFile: 'reports/json/results.json' }],

    /* Custom reporter — logs test lifecycle events */
    ['./helpers/custom-reporter.js'],
  ],

  // ── Output directory for artifacts ────────────────────────────────────────
  outputDir: './test-results',

  // ── Browser projects ──────────────────────────────────────────────────────
  projects: [
    // ── Setup project: runs global auth once ──────────────────────────────
    // { name: 'setup', testMatch: /.*\.setup\.js/ },

    // ── Desktop browsers ──────────────────────────────────────────────────
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome', // use installed Chrome; remove to use bundled Chromium
      },
      // dependencies: ['setup'],
    },
    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },
    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    // ── Mobile emulation ──────────────────────────────────────────────────
    // {
    //   name: 'mobile-chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'mobile-safari',
    //   use: { ...devices['iPhone 13'] },
    // },
  ],
});
